version: '3.8'

services:
  db:
    image: postgres:15
    container_name: effective_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: effective
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@db:5432/effective?sslmode=disable",
      "up"
    ]
    restart: on-failure

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/effective?sslmode=disable
    depends_on:
      - db
      - migrate
    ports:
      - "8080:8080"
    env_file:
      - .env
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/effective?sslmode=disable
    volumes:
      - .:/app

volumes:
  db_data:

