# Dockerfile.test
FROM golang:1.23

WORKDIR /app

# Копируем модули и зависимости для кэширования
COPY go.mod go.sum ./
RUN go mod download

# Копируем весь код
COPY . .

# Точка входа — запускаем тесты
CMD ["go", "test", "./...", "-v"]
